
export const SOCKS_VERSION = 0x05;

export enum AUTH_METHODS {
    NO_AUTHENTICATION_REQUIRED = 0x00,
    GSSAPI = 0x01,
    USERNAME_PASSWORD = 0x02,
    NO_ACCEPTABLE_METHODS = 0xFF,
}

export enum CONNECTION_STAGES {
    GREETING,
    AUTHENTICATION,
    REQUEST,
    RELAY,
}

export enum ADDRESS_TYPE {
    IPv4 = 0x01,
    DOMAINNAME = 0x03,
    IPv6 = 0x04,
}


export enum COMMANDS {
    CONNECT = 0x01,
    BIND = 0x02,
    UDP_ASSOCIATE = 0x03,
}


export enum REPLIES {
    SUCCEEDED = 0x00,
    GENERAL_FAILURE = 0x01,
    CONNECTION_NOT_ALLOWED = 0x02,
    NETWORK_UNREACHABLE = 0x03,
    HOST_UNREACHABLE = 0x04,
    CONNECTION_REFUSED = 0x05,
    TTL_EXPIRED = 0x06,
    COMMAND_NOT_SUPPORTED = 0x07,
    ADDRESS_TYPE_NOT_SUPPORTED = 0x08,
}